Support passing build handle as version param, arg check

diff --git a/default/upgrade-gateway b/default/upgrade-gateway
--- a/default/upgrade-gateway
+++ b/default/upgrade-gateway
@@ -3,11 +3,25 @@
 REPOSITORY=$1
 VERSION=$2
 MODE=$3
+ARGCOUNT=0
 
+for var in "$@"; do 
+    (( ARGCOUNT++ ))
+done
+
+if (( $ARGCOUNT < 2 || $ARGCOUNT > 3 )); then
+    echo "Invalid number of args"
+    echo "$*"
+elif [[ ! $(echo $VERSION|grep "^[0-9A-Z_]\+/[0-9A-Z_]\+-\([0-9]\+\|latest\)$") ]]; then
+    echo "Version $VERSION is not valid"
+    exit 1
+fi
+
+exit 0
 if [[ -f /DATYPE ]]; then
-  /usr/local/storediq/bin/fastupdate.py
+  /usr/local/storediq/bin/fastupdate.py $VERSION
 else
-  /spinmini --noreboot TRUNK/STOREDIQ s gw
+  /spinmini --noreboot $VERSION s gw
 fi
 
 if [[ $MODE == production ]]; then
@@ -15,3 +29,4 @@ if [[ $MODE == production ]]; then
 elif [[ $MODE == idle ]]; then
   service deepfiler stop
 fi
+
